pages:
  stage: deploy
  image: nixpkgs/nix:latest
  script:
    - mkdir -p /etc/nix
    # Sandboxing would require privileged docker.
    - echo 'sandbox = false' > /etc/nix/nix.conf
    # Enable flakes
    - echo 'experimental-features = nix-command flakes' >> /etc/nix/nix.conf
    # Build the docs.
    - cd docs/
    - nix develop .#website -c zola build
    - mv public/ ..
  artifacts:
    paths:
      - public/
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
